export const projects = [
  {
    name: "Aarc",
    desc: "One click multi chain deposits for any wallet or dApp",
    image: "/images/ventures/aarc.png",
    link: "https://aarc.xyz",
  },
  {
    name: "Alloc8",
    desc: "Agentic liquidity delegation via smart accounts",
    image: "/images/ventures/alloc8.png",
    link: "https://www.alloc8.xyz/",
  },
  {
    name: "Brahma",
    desc: "Autonomous systems for cross-chain capital automation",
    image: "/images/ventures/brahma.png",
    link: "https://brahma.fi/",
  },
  {
    name: "Clave",
    desc: "All-in-one mobile app for onchain finance",
    image: "/images/ventures/clave.png",
    link: "https://www.getclave.com/",
  },
  {
    name: "CoinShift",
    desc: "Unified treasury, payouts, and yield management platform",
    image: "/images/ventures/coinshift.png",
    link: "https://www.coinshift.xyz/",
  },
  {
    name: "Epoch Protocol",
    desc: "Intent-based cross-chain execution abstraction layer",
    image: "/images/ventures/epoch.png",
    link: "https://epochprotocol.xyz",
  },
  {
    name: "Fileverse",
    desc: "Decentralized, censorship-resistant Docs and Sheets.",
    image: "/images/ventures/fileverse.png",
    link: "https://fileverse.io/",
  },
  {
    name: "Hats Finance",
    desc: "Intent-based cross-chain execution abstraction layer",
    image: "/images/ventures/hats.png",
    link: "https://hats.finance/",
  },
  {
    name: "HOPR",
    desc: "Incentivized mixnet for private data exchange",
    image: "/images/ventures/hopr.png",
    link: "https://www.hoprnet.org/",
  },
  {
    name: "Interfacer",
    desc: "Social trading network for markets and copy trading",
    image: "/images/ventures/interfacer.png",
    link: "https://interface.social",
  },
  {
    name: "Join",
    desc: "Unified crypto ecosystem bridging retail and institutional DeFi",
    image: "/images/ventures/join.png",
    link: "https://getjoin.io",
    isSafeAligned: true,
  },
  {
    name: "Karpatkey",
    desc: "Onchain asset management and liquidity network platform",
    image: "/images/ventures/karpatkey.png",
    link: "https://kpk.io/",
  },
  {
    name: "Mezzanine",
    desc: "App Store for global businesses with enterprise features",
    image: "/images/ventures/mezzanine.png",
    link: "https://www.mezzanine.xyz/",
  },
  {
    name: "Metal",
    desc: "Token presale launch platform on Base",
    image: "/images/ventures/metal.png",
    link: "https://metal.build/",
  },
  {
    name: "Onit",
    desc: "A highly configurable prediction market protocol",
    image: "/images/ventures/onit.png",
    link: "https://onit.fun/",
  },
  {
    name: "Openfort",
    desc: "Open-source wallet infra with auth and payments.",
    image: "/images/ventures/openfort.png",
    link: "https://www.openfort.io",
  },
  {
    name: "Palmera",
    desc: "Safe infra provider across 25+ EVM chains",
    image: "/images/ventures/palmera.png",
    link: "https://www.palmeradao.xyz/",
  },
  {
    name: "Picnic",
    desc: "Web2 like DeFi experience for the Latam market",
    image: "/images/ventures/picnic.png",
    link: "https://usepicnic.com/en",
  },
  {
    name: "Pimlico",
    desc: "Advanced smart account infra built on ERC-4337",
    image: "/images/ventures/pimlico.png",
    link: "https://www.pimlico.io/",
  },
  {
    name: "PWN",
    desc: "Universal lending protocol for the tokenized economy",
    image: "/images/ventures/pwn.png",
    link: "https://pwn.xyz/",
  },
  {
    name: "Rhinestone",
    desc: "Intent-powered API for seamless onchain UX",
    image: "/images/ventures/rhinestone.png",
    link: "https://www.rhinestone.dev/",
  },
  {
    name: "Sablier",
    desc: "Onchain token distribution for payroll and vesting",
    image: "/images/ventures/sablier.png",
    link: "https://sablier.com",
  },
  {
    name: "Safe {Wallet}",
    desc: "Gold standard for self-custodial treasury management",
    image: "/images/ventures/safe-wallet.png",
    link: "https://safe.global",
  },
  {
    name: "Superfluid",
    desc: "Protocol for money streaming on Ethereum",
    image: "/images/ventures/superfluid.png",
    link: "https://superfluid.org/",
  },
  {
    name: "Wildcat finance",
    desc: "Configurable under-collateralised credit rails to Ethereum",
    image: "/images/ventures/wildcat.png",
    link: "https://app.wildcat.finance/",
  },
  {
    name: "World",
    desc: "Proof of personhood & universal basic income",
    image: "/images/ventures/world.png",
    link: "https://world.org/",
    isSafeAligned: true,
  },
  {
    name: "Zodiac",
    desc: "Composable DAO tooling built on open standards",
    image: "/images/ventures/zodiac.png",
    link: "https://www.zodiac.wiki/",
  },
  {
    name: "ZKsync foundation",
    desc: "Zk based Ethereum L2 building Incorruptible financial infra",
    image: "/images/ventures/zksync.png",
    link: "https://www.zksync.io/",
    isSafeAligned: true,
  },
];
