export const validatorTermsData = {
  title: "Terms and Conditions",
  text: `<p><strong>Validator Operation on Safenet Beta</strong></p>
<p><em>Last updated: March 2026</em></p>
<p>1. Please read the following Terms and Conditions carefully as they set out a legally binding agreement between you and the Safe Ecosystem Foundation, a Swiss foundation with registered office at Bahnhofstrasse 16, 6300 Zug, Switzerland (the &ldquo;<strong>Foundation</strong>&rdquo;). These terms (&ldquo;<strong>Terms</strong>&rdquo;) govern your participation as a validator (the &ldquo;<strong>Validator(s)</strong>&rdquo;) on Safenet Beta. If you do not accept these Terms or any part thereof, you may not operate a validator node (the &ldquo;<strong>Validator Node</strong>&rdquo;) on Safenet Beta. Your operation of a Validator Node implies your acceptance of these Terms.</p>
<p>2. In these Terms, references to &ldquo;you&rdquo; refer to the entity and/or individual operating a Validator Node on Safenet Beta.</p>
<p>3. The Foundation may amend these Terms from time to time at its own discretion. By continuing to operate as a Validator, you agree to and accept to be bound by the latest version of the Terms. The latest version of the Terms always applies and is accessible at <a href="https://safefoundation.org/safenet/validatorterms">https://safefoundation.org/safenet/validatorterms</a>.</p>
<p>4. Other terms outside of these Terms may apply to you (vis-&agrave;-vis the respective third-parties) if you use and access other websites. Such other terms apply separately or in addition to these Terms (vis-&agrave;-vis the respective third-parties). We are not responsible and/or liable for any aspect of and/or for any damages arising out of or related to any kind of products or services provided by third-parties.</p>
<h2>1. Introduction</h2>
<p>5. These Terms set forth the rights and obligations of Validators in connection with operating a Validator Node on Safenet Beta, a permissioned, validator-based consensus layer developed by the Foundation (&ldquo;<strong>Safenet Beta</strong>&rdquo;). Safenet Beta enables Validators to confirm and validate transactions that occur on Safenet Beta. These Terms define the technical, operational, and compliance conditions under which Validators are permitted to participate in the Safenet Beta network.</p>
<p>6. Safenet Beta is an experimental release intended for testing purposes. Participation as a Validator is limited to a permissioned set of technically qualified independent operators who have been selected by the Foundation. The Foundation does not act as a co-operator, custodian, employer, or principal of Validators.</p>
<h2>2. Safenet Beta</h2>
<h3>Overview</h3>
<p>7. Safenet Beta is the first release of Safenet, a decentralized, validator-based consensus layer that enforces basic on-chain transaction security checks using the SAFE token (&ldquo;<strong>SAFE Token</strong>&rdquo;) as its core security primitive, before broader integrations and tokenomics are introduced. Safenet Beta launches with a permissioned validator set of 4&ndash;6 Validators.</p>
<p>8. The network relies on independent Validator Nodes to operate, including the validation of transactions, production and verification of attestations / blocks, maintenance of network security, and support of the network&rsquo;s consensus mechanism. All validation activities are carried out solely by you through your own Validator Node and infrastructure.</p>
<p>9. The Foundation does not perform validation, transaction execution, or node management on your behalf and does not operate, supervise, or monitor individual Validator Nodes. The Foundation assumes no responsibility for validator performance, availability, or network outcomes.</p>
<h3>SAFE Token</h3>
<p>10. The SAFE Token is a blockchain-based utility token issued by the Foundation, based on the ERC-20 token standard of the Ethereum blockchain. The SAFE Token serves as the core security and coordination primitive of Safenet Beta and can be used to govern the SafeDAO as well as to participate in Safe DAO votings <a href="https://safefoundation.org/token">https://safefoundation.org/token</a>.</p>
<h3>Validator Node</h3>
<p>11. A Validator Node is a computer server on the network used to monitor, audit, confirm, or validate transactions on Safenet Beta. You are solely responsible for all hardware, software, hosting, and infrastructure costs necessary to operate your Validator Node.</p>
<p>12. The Validator Node exists independently and is operated by you under your own technical environment and infrastructure. Your operation of a Validator Node is governed exclusively by these Terms, the applicable documentation as attached in Annex 1 of these Terms (the &ldquo;<strong>Documentation</strong>&rdquo;) and the network rules.</p>
<p>13. Through the network, SAFE Token holders may delegate SAFE Tokens to your Validator Node in accordance with the rules of the applicable staking smart contract. Any such delegation constitutes a direct interaction between the delegator, the staking contract, and your Validator Node.</p>
<p>14. The source code of the Validator is publicly available for reference at: <a href="https://github.com/safe-research/safenet/tree/beta/validator/">https://github.com/safe-research/safenet/tree/beta/validator/</a></p>
<h3>Staking Contract</h3>
<p>15. The delegation and staking smart contract (&ldquo;<strong>Staking Contract</strong>&rdquo;) is a self-executing software program originally deployed on the Ethereum blockchain. The Staking Contract operates autonomously in accordance with its programmed logic and the rules of the underlying blockchain protocol.</p>
<p>16. You may receive delegated SAFE Token from independent third-party stakers through the Staking Contract. Any such delegation constitutes a direct interaction between delegators and the Staking Contract referencing your Validator Node address, and does not involve the Foundation acting as an intermediary.</p>
<p>17. The Foundation does not retain any administrative access (with the exception of permissioning validators for Safenet Beta), upgrade rights, pause functionality, governance control, or other ability to modify, influence, or intervene in the operation of the Staking Contract after deployment. The Foundation cannot approve, reject, modify, reverse, delay, censor, or otherwise interfere with any transaction submitted to the Staking Contract.</p>
<p>18. The source code of the Staking Contract is publicly available for reference at: <a href="https://github.com/safe-research/safenet/blob/beta/contracts/src/Staking.sol">https://github.com/safe-research/safenet/blob/beta/contracts/src/Staking.sol</a></p>
<h3>Consensus and Coordinator Contracts</h3>
<p>19. The consensus and coordinator smart contracts (together the &ldquo;<strong>Safenet Beta Contracts</strong>&rdquo;) are self-executing software programs deployed on Gnosis Chain.</p>
<p>20. The Safenet Beta Contracts operate autonomously in accordance with their programmed logic and the rules of the underlying blockchain protocol. These contracts facilitate, among other things, the coordination of validator attestations, the verification of Safenet Beta security checks, and the ordering and confirmation of transactions submitted to Safenet Beta.</p>
<p>21. The Foundation does not retain any administrative access, upgrade rights, pause functionality, governance control, or other ability to modify, influence, or intervene in the operation of the Safenet Beta Contracts after deployment.</p>
<p>22. The Foundation cannot approve, reject, modify, reverse, delay, censor, or otherwise interfere with any transaction processed by the Safenet Beta Contracts.</p>
<p>23. All interactions with the Safenet Beta Contracts occur directly between Validators, network participants, and the underlying blockchain infrastructure. The Foundation does not act as an intermediary or operator of these interactions.</p>
<p>24. The source code of the Safenet Beta Contracts is publicly available for reference at: <a href="https://github.com/safe-research/safenet/blob/beta/contracts/src/Consensus.sol">https://github.com/safe-research/safenet/blob/beta/contracts/src/Consensus.sol</a> and <a href="https://github.com/safe-research/safenet/blob/beta/contracts/src/FROSTCoordinator.sol">https://github.com/safe-research/safenet/blob/beta/contracts/src/FROSTCoordinator.sol</a></p>
<h3>Transaction Fees</h3>
<p>25. Since the Staking Contract is deployed on the Ethereum blockchain, interactions with the Staking Contract require the payment of blockchain transaction fees in the native digital asset of the Ethereum blockchain (ETH) (&ldquo;<strong>ETH Transaction Fees</strong>&rdquo;).</p>
<p>26. ETH Transaction Fees are determined exclusively by the Ethereum blockchain network and depend on network conditions at the time a transaction is submitted. ETH Transaction Fees may be subject to significant volatility and are non-refundable.</p>
<p>27. ETH Transaction Fees are paid directly by you to the blockchain network and are not charged, collected, received, or controlled by the Foundation. The Foundation does not determine, influence, subsidize, or reimburse any ETH Transaction Fees.</p>
<p>28. The Foundation does not guarantee that any transaction submitted by you will be successfully processed or confirmed by the blockchain network and shall not be responsible for any failed, delayed, or cancelled transactions resulting from insufficient ETH Transaction Fees or network conditions.</p>
<p>29. Since the Safenet Beta Contracts are deployed on Gnosis Chain, interactions with the Safenet Beta Contracts require the payment of blockchain transaction fees in the native digital asset of Gnosis chain (XDAI) (&ldquo;<strong>XDAI Transaction Fees</strong>&rdquo;).</p>
<p>30. XDAI Transaction Fees are determined exclusively by the Gnosis chain network and depend on network conditions at the time a transaction is submitted. XDAI Transaction Fees may be subject to significant volatility and are non-refundable.</p>
<p>31. XDAI Transaction Fees are paid directly by you to the blockchain network and are not charged, collected, received, or controlled by the Foundation. The Foundation does not determine, influence, subsidize, or reimburse any XDAI Transaction Fees.</p>
<p>32. The Foundation does not guarantee that any transaction submitted by you will be successfully processed or confirmed by the blockchain network and shall not be responsible for any failed, delayed, or cancelled transactions resulting from insufficient XDAI Transaction Fees or network conditions.</p>
<h2>3. Eligibility and Restricted Jurisdictions</h2>
<p>33. You hereby represent and warrant that you:</p>
<ol type="i">
<li>have the right, authority, and legal capacity to accept these Terms and that you are of the legal majority age in your country or jurisdiction of residence;</li>
<li>will not operate a Validator Node if the laws of your countries of residency and/or citizenship prohibit you from doing so in accordance with these Terms;</li>
<li>are not subject to personal sanctions issued by the UN, US, EU (EU member states), UK, Japan or Switzerland;</li>
<li>only operate a Validator Node for your own personal use;</li>
<li>do not operate a Validator Node from, and are not a resident of, nor an entity organized, incorporated or doing business in any country or jurisdiction to which the Swiss State Secretariat for Economic Affairs (SECO), the United States, the United Kingdom, the European Union or any of its member states, or the United Nations has imposed embargoes or sanctions, including, but not limited to: Belarus, Burundi, Central African Republic, Congo, DPRK (North Korea), Guinea, Guinea-Bissau, Iran, Iraq, Lebanon, Libya, Mali, Myanmar (Burma), Republic of South Sudan, Russia, Somalia, Sudan, Syria, Ukraine (Donbas region), Venezuela, Yemen, or Zimbabwe (&ldquo;<strong>Restricted Jurisdictions</strong>&rdquo;);</li>
<li>are not (a) the subject of asset freeze, travel ban, financial, economic, human rights, sectoral or trade sanctions administered or enforced by any governmental authority, or otherwise designated on any list of prohibited or restricted parties; and</li>
<li>do not intend to transact with any sanctioned person as set out in (iii) or any person in any Restricted Jurisdiction with regard to Transaction Fees received.</li>
</ol>
<p>34. We have the right to exclude you from operating a Validator Node at our sole discretion and for any reason, such as violation of these Terms.</p>
<h2>4. Validator Obligations and Node Operation</h2>
<h3>4.1 Establishment and Maintenance of Validator Node</h3>
<p>35. During the term of these Terms, you shall operate and maintain a Validator Node necessary to validate transactions on Safenet Beta in accordance with the Documentation. You must comply with all technical specifications, network rules, and operational guidance issued by the Foundation from time to time.</p>
<h3>4.2 Operational Duties</h3>
<p>36. You shall maintain reliable uptime and connectivity; process and attest to transactions according to the provided network ruleset; follow all technical specifications, updates, and operational guidance; and act in good faith to support network testing objectives.</p>
<p>37. In particular, you shall check and attest to (i) all executed safe transactions submitted to Safenet Beta, and (ii) all additional transactions explicitly added to Safenet Beta.</p>
<p>38. You may operate as a Validator only for lawful purposes and in accordance with these Terms. You agree not to use the network: (i) for any unlawful, fraudulent, or malicious purpose; (ii) to upload, transmit, or distribute any viruses, worms, malware, ransomware, or other harmful code; (iii) to attempt to interfere with, compromise the integrity or security of, or reverse engineer Safenet Beta or its underlying infrastructure; (iv) to access or attempt to access accounts, networks, or data that you are not authorized to use; (v) to engage in any activity that could disable, overburden, or impair the proper functioning of the network; and/or (vi) in any way that violates any applicable law or regulation.</p>
<h3>4.3 Minimum Stake</h3>
<p>39. You shall stake at least 3,500,000 SAFE Token on your Validator Node on Ethereum Mainnet (Self-Delegated Stake). You further acknowledge and agree that any SAFE Token holder may additionally stake SAFE Token on your Validator Node (Delegated Stake).</p>
<h3>4.4 Validator Node Operation</h3>
<p>40. The Validator shall be solely responsible for all costs (including electrical energy costs) and expenses for its activities under these Terms, including for acquiring, installing, maintaining, and securing all hardware, software, hosting, and other equipment for its Validator Node(s).</p>
<h3>4.5 Validator Node Security</h3>
<p>41. You will establish and maintain reasonable and appropriate safeguards to protect your Validator Node and Validator systems against unauthorized use, destruction, loss, or alteration of the Validator Node and associated digital assets. These safeguards shall include network and data security measures consistent with information technology industry standards (e.g., firewalls, monitoring, and counteraction of external intrusion, regular back-up of systems and data, and troubleshooting).</p>
<p>42. If you discover or are notified of a breach or potential breach of security relating to your Validator Node or Validator Systems, you will immediately (i) notify all other known Validators and the Foundation of such breach or potential breach, (ii) investigate and cure the breach or potential breach, and (iii) provide the Foundation with reasonable assurance that such breach or potential breach will not recur.</p>
<p>43. You will maintain, patch, and update your Validator Systems on a regular and timely basis in accordance with best industry practices. You agree that you will not introduce, and will take all required measures to prevent the introduction of, any Malicious Code into your Validator Systems.</p>
<p>44. By participating as a Validator, you represent that you are financially and technically sophisticated enough to understand the inherent risks associated with using cryptographic and blockchain-based systems, especially staking systems, and that you have a working knowledge of digital assets, validator operations, and blockchain infrastructure. You further understand that blockchain-based transactions are irreversible and public. The markets for digital assets are highly volatile due to factors including adoption, speculation, technology, security, and regulation. You acknowledge and accept the risk that staked assets may lose some or all of their value, and that you may experience significant operational and financial costs associated with running a Validator Node. Accordingly, you understand and agree to assume full responsibility for all risks of participating as a Validator on Safenet Beta.</p>
<h3>4.6 Non-Exclusive Relationship</h3>
<p>45. The specific arrangements referred to herein shall not exclude or limit either party from entering into any relationship with any other party.</p>
<h2>5. Rewards</h2>
<h3>5.1 Reward Basis</h3>
<p>46. Validator rewards (&ldquo;<strong>Rewards</strong>&rdquo;) are determined based on (i) your total stake and (ii) your measured participation rate during the applicable evaluation period. No rewards shall accrue for any period in which your participation rate falls below the threshold as defined in the network rules (currently seventy-five percent (75%); subject to change at the fullest discretion of the Foundation).</p>
<p>47. You are entitled to receive a commission equal to five percent (5%, subject to change at the sole discretion of the Foundation) of rewards attributable to delegated stake, which commission shall be deducted prior to distribution to delegators. All reward distributions occur on Ethereum.</p>
<h3>5.2 Distribution Process</h3>
<p>48. You and delegators must actively claim rewards; unclaimed rewards are not automatically delivered. You solely bear the associated claiming costs.</p>
<h3>5.3 DAO Proposal</h3>
<p>49. Payment of any Rewards is contingent upon prior approval by SafeDAO (&ldquo;<strong>SafeDAO</strong>&rdquo;). The Foundation and/or any other party intends to submit a dedicated governance proposal to SafeDAO for this purpose. Until such proposal has been approved in accordance with the applicable SafeDAO governance rules, no Rewards shall accrue or become payable.</p>
<h3>5.4 No Guarantee of Rewards</h3>
<p>50. All Rewards described herein are fully discretionary, experimental, and provided solely to support testing and evaluation of Safenet Beta. Nothing in these Terms shall be construed as creating any obligation on the part of the Foundation or any of its affiliates to continue, maintain, or future-fund rewards, subsidies, or any other form of compensation. You are not entitled to any reimbursement of expenses.</p>
<h3>5.5 No Slashing</h3>
<p>51. In Safenet Beta, no slashing is possible. Validators and delegators are not subject to slashing such as stake reduction for downtime, misconfiguration, or other operational faults.</p>
<h2>6. Legal Relationship Between You and the Foundation</h2>
<h3>6.1 Role of the Foundation</h3>
<p>52. The Foundation&rsquo;s role is strictly limited to developing and promoting the Safenet Beta network and selecting the permissioned Validator set. The Foundation does not provide staking services, validation services, asset management, custody, brokerage, advisory, or any other financial or investment-related services.</p>
<p>53. Nothing in these Terms shall be construed as creating any employment, partnership, agency, fiduciary, or trust relationship between you and the Foundation. The Foundation does not act on behalf of Validators and does not assume any duty to act in the economic interest of Validators.</p>
<h3>6.2 No Control over Validator Operations</h3>
<p>54. At no time does the Foundation have possession, custody, control, or disposal power over your Validator Node, Validator Systems, or associated digital assets. All validation, transaction attestation, and node management activities are initiated, authorized, and executed exclusively by you through your own infrastructure.</p>
<h3>6.3 No Obligation to Monitor or Intervene</h3>
<p>55. The Foundation has no obligation to monitor the Staking Contract, staking activities, Validator Nodes, or blockchain network conditions and is under no duty to warn Validators of any risks, vulnerabilities, exploits, or adverse events.</p>
<p>56. The Foundation does not assume any obligation to intervene, suspend, mitigate, reverse, or remedy any losses or adverse effects arising from the operation of a Validator Node or participation in Safenet Beta.</p>
<h3>6.4 No Investment or Financial Product</h3>
<p>57. Validator participation in Safenet Beta does not constitute an investment product, collective investment scheme, financial instrument, or financial service under applicable law. You acknowledge that participation involves technological and economic risks.</p>
<h3>6.5 Discontinuation of Safenet Beta</h3>
<p>58. The Foundation may discontinue, suspend, or permanently cease the operation or availability of Safenet Beta, in whole or in part, at any time and at its discretion, including upon the launch of Safenet, which will replace Safenet Beta.</p>
<p>59. The Foundation may, but is not obligated to, provide advance notice of any such discontinuation. The Foundation shall not be liable for any losses or disadvantages resulting from the discontinuation or unavailability of Safenet Beta.</p>
<h3>6.6 KYC and Compliance</h3>
<p>60. You will promptly provide the Foundation and its service providers with the documents reasonably requested to fulfil documentation requirements under any applicable customer due diligence (&ldquo;<strong>CDD</strong>&rdquo;), know your customer (&ldquo;<strong>KYC</strong>&rdquo;), and anti-money laundering (&ldquo;<strong>AML</strong>&rdquo;) regulations or requirements.</p>
<h3>6.7 Records</h3>
<p>61. To the extent necessary and required by the Foundation, the Validator will provide and maintain documents, files, and other information necessary for the Foundation and pertaining to their activity for Safenet Beta (&ldquo;<strong>Records</strong>&rdquo;) during the Term.</p>
<h3>6.8 Audit Rights</h3>
<p>62. Upon reasonable notice, the Foundation or its authorized representatives shall have the right to access, inspect, and audit such Records. You shall fully cooperate with any audit or inspection, including providing necessary explanations, documentation, and access to systems as reasonably requested.</p>
<h3>6.9 General Disclaimers and Disclaimed Warranty</h3>
<p>63. The Foundation makes no representations or warranties with respect to Safenet Beta, including its security, availability, or economic outcomes. Safenet Beta is made available on an &ldquo;as-is&rdquo; and &ldquo;as-available&rdquo; basis. The Foundation hereby expressly disclaims all representations and/or warranties of any kind, express or implied, including all warranties of merchantability, fitness for a particular purpose, non-infringement, or any warranty regarding the amount of Rewards or other economic benefit.</p>
<p>64. The Foundation does not warrant that Safenet Beta will operate uninterrupted or be error-free, and makes no warranty concerning the accuracy, reliability, or completeness of any information or data obtained or derived through the use of Safenet Beta. The Foundation disclaims any responsibilities with respect to access of data from or the functioning of Nodes on Ethereum and/or any other blockchain (e.g. Gnosis chain).</p>
<h3>6.10 Limitation of Liability</h3>
<p>65. By accepting these Terms, you understand and acknowledge that the Foundation shall not be liable for any damages, losses, or injuries caused by or otherwise related to your participation in Safenet Beta or your operation of a Validator Node, under any cause or action whatsoever in any jurisdiction, including actions for breach of warranty, breach of contract, or tort.</p>
<p>66. In particular, the Foundation will not be responsible or liable to you for any losses, damages, or claims arising from: (1) operational errors, including misconfigured nodes or incorrect transactions; (2) server failure or data loss; (3) corrupted systems or data; (4) viruses or other technologically harmful material affecting your systems; or (5) validator performance or outcomes, including downtime, double-signing, censorship, or failure to distribute rewards.</p>
<p>67. Our liability is limited to direct damages arising out of acts of intent and gross negligence. Any liability for indirect damages or consequential damages, including loss of profit, and/or damages arising out of negligent conduct, to the maximum extent permitted by applicable law, is expressly excluded.</p>
<h3>6.11 Indemnification</h3>
<p>68. You agree to indemnify, and hold us harmless, against any and all liabilities, damages, costs, expenses and claims (including third party claims) arising out of or in connection with your breach of the Terms or violation of applicable law.</p>
<h3>6.12 Personal Data</h3>
<p>69. For information about how we handle your personal information, please see our privacy policy at <a href="https://safefoundation.org/privacy">https://safefoundation.org/privacy</a>.</p>
<h3>6.13 Intellectual Property Rights</h3>
<p>70. Each party shall retain all right, title, and interest in and to its intellectual property rights. Nothing in these Terms is intended to, nor shall it be construed to, transfer, assign, or grant any IP rights of either party, except as may be explicitly agreed in a separate written agreement.</p>
<h2>7. Miscellaneous</h2>
<h3>7.1 No Assignment</h3>
<p>71. You shall not assign, transfer or otherwise deal with all or any of its rights or obligations under these Terms without our prior written consent.</p>
<h3>7.2 Entire Agreement and Severability</h3>
<p>72. These Terms contain the entire agreement between the Foundation and you regarding the subject matter hereof and supersedes all understandings and agreements whether written or oral. If any provision of these Terms is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other provision of these Terms or invalidate or render unenforceable such provision in any other jurisdiction. Upon such determination that any provision is invalid, illegal, or unenforceable, these Terms shall be modified to effectuate the original intent of the parties as closely as possible.</p>
<h3>7.3 Governing Law and Jurisdiction</h3>
<p>73. These Terms shall be governed by and construed in accordance with substantive <strong>Swiss law</strong>, excluding the Swiss conflict of law rules. The application of the United Nations Convention for Contracts for the International Sale of Goods (CISG) is hereby expressly excluded.</p>
<p>74. Any dispute arising out of or in conjunction with these Terms shall be submitted to the exclusive jurisdiction of the ordinary courts of Zug, Switzerland.</p>
<h3>7.4 Class Action Waiver</h3>
<p>75. To the fullest extent permitted by any applicable law, you waive your right to participate in a class action lawsuit or a class-wide arbitration against us or any individual or entity involved in the operation of Safenet Beta.</p>
<h3>7.5 Notices</h3>
<p>76. To be valid, all notices permitted or required under these Terms must be sent in writing, via certified mail (or email followed by certified mail), to the address set forth in these Terms. Notices will be deemed given on receipt by the applicable party.</p>
<h3>7.6 Queries, Remarks and Suggestions</h3>
<p>77. For any queries, remarks or suggestions, please contact the Foundation using the contact details below:</p>
<p><strong>March 2026</strong></p>
<p><strong>The Safe Ecosystem Foundation</strong><br>Bahnhofstrasse 16, 6300 Zug, Switzerland<br>Email: <a href="mailto:legal@safefoundation.org">legal@safefoundation.org</a></p>`,
};
